spring:
  application:
    name: config-server-aman

eureka:
  instance:
    ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1010/eureka
